# Generated by Django 3.2.9 on 2021-12-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=20, verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.ImageField(upload_to='color/', verbose_name='颜色图片地址'),
        ),
        migrations.AlterField(
            model_name='color',
            name='colorname',
            field=models.CharField(max_length=10, verbose_name='颜色名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net_shop_app.category', verbose_name='类别ID'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gdesc',
            field=models.CharField(max_length=100, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gname',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gdurl',
            field=models.ImageField(upload_to='', verbose_name='详情图片地址'),
        ),
        migrations.AlterField(
            model_name='goodsdetailname',
            name='gdname',
            field=models.CharField(max_length=30, verbose_name='详情名称'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.PositiveIntegerField(verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_set', to='net_shop_app.goods'),
        ),
        migrations.AlterField(
            model_name='size',
            name='sname',
            field=models.CharField(max_length=10, verbose_name='尺寸名称'),
        ),
    ]
